name = "Ballistics"
uuid = "92afdc1b-fc5c-47ce-9813-62db66c25070"
authors = ["Irene Ndindabahizi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
